packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.510.0
  tailwindcss: ^4.0.15
  typescript: ^5.6.3
  "@types/node": ^22.15.21
  tailwind-merge: ^3.3.0
  tw-animate-css: ^1.2.9
  postcss: ^8.5.3
catalogs:
  prisma:
    prisma: latest
    "@prisma/client": latest
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2
